import { BookingCard } from "@/src/components/BookingCard";
import { ConfirmationModal } from "@/src/components/ConfirmationModal";
import { useBarbershopCurrent } from "@/src/features/barbershop/hooks";
import { BarbershopSwitcherModal } from "@/src/features/home/components/BarbershopSwitcherModal";
import { NewBookBottomSheet } from "@/src/components/NewBookBottomSheet";
import { ShortcutTile } from "@/src/features/home/components/ShortcutTile";
import {
  HOME_QUERY_KEYS,
  useBookingSummary,
  useCurrentPin,
  useGenerateWalkInPin,
  useHomeActiveBookings,
} from "@/src/features/home/hooks";
import { QueueStatCard } from "@/src/features/home/components/QueueStatCard";
import { useOpenHours } from "@/src/hooks/useOpenHours";
import { useUnreadNotificationsCount } from "@/src/features/notifications/hooks";
import { useUnreadCountByOrg } from "@/src/features/notifications/hooks/useNotificationsQueries";
import { notificationsService } from "@/src/features/notifications/services/notifications.service";
import { pwaNotificationService } from "@/src/services/pwa-notification.service";
import { mapApiStatusToBookingStatus } from "@/src/features/schedule/utils/booking-formatters";
import { useRequestedBookings } from "@/src/features/schedule/hooks";
import { useAuthUser, useMemberRole } from "@/src/hooks";
import { authClient } from "@/src/lib/auth-client";
import { useI18nContext } from "@/src/lib/i18n/provider";
import { useToast } from "@/src/lib/providers";
import { Colors } from "@/src/theme/colors";
import { formatTime12h, parseTime24, toApiDate } from "@/src/utils/date";
import { formatTimeRange } from "@/src/utils/time-format";
import { Ionicons } from "@expo/vector-icons";
import { useQueryClient } from "@tanstack/react-query";
import * as Clipboard from "expo-clipboard";
import { useRouter } from "expo-router";
import React, { useEffect, useRef, useState } from "react";
import { AppText } from "@/src/components/AppText";
import {
  ActivityIndicator,
  Animated,
  Image,
  NativeScrollEvent,
  NativeSyntheticEvent,
  StyleSheet,
  TouchableOpacity,
  View,
} from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";

const TOP_BAR_HEIGHT = 52;

function getStatConfig(t: (key: string) => string): {
  key: string;
  label: string;
  icon: React.ComponentProps<typeof Ionicons>["name"];
}[] {
  return [
    {
      key: "walkIn",
      label: t("home.walkInShort"),
      icon: "walk",
    },
    {
      key: "appointment",
      label: t("home.appointShort"),
      icon: "calendar",
    },
  ];
}

export function HomeDashboardScreen() {
  const { t } = useI18nContext();
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const today = toApiDate(new Date());
  const toast = useToast();

  const queryClient = useQueryClient();
  const { user } = useAuthUser();
  const { data: barbershop } = useBarbershopCurrent();
  const { data: summary } = useBookingSummary(today);
  const { data: activeBookings = [] } = useHomeActiveBookings(today);
  const nextYear = toApiDate(new Date(Date.now() + 365 * 86400 * 1000));
  const { data: requestsData = [] } = useRequestedBookings(today, nextYear);
  const requestCount = requestsData.length;
  const { data: currentPinData } = useCurrentPin();
  const { mutate: generatePin, isPending: isGenerating } =
    useGenerateWalkInPin();
  const { role } = useMemberRole();
  const { data: unreadCount } = useUnreadNotificationsCount();
  const { data: unreadByOrg = [] } = useUnreadCountByOrg();
  const { data: sessionData } = authClient.useSession();

  const otherOrgHasUnread = unreadByOrg.some(
    (item) =>
      item.organizationId !== sessionData?.session?.activeOrganizationId &&
      item.count > 0,
  );
  const { data: openHoursData } = useOpenHours();

  const [switcherVisible, setSwitcherVisible] = useState(false);
  const [newBookVisible, setNewBookVisible] = useState(false);
  const [notifConsentVisible, setNotifConsentVisible] = useState(false);

  // Silently renew push subscription on mount if permission was already granted
  useEffect(() => {
    if (
      typeof window === "undefined" ||
      !("Notification" in window) ||
      Notification.permission !== "granted"
    )
      return;
    pwaNotificationService
      .requestPermission()
      .then(({ subscription }) => {
        if (subscription) {
          notificationsService
            .registerWebPush(
              subscription as {
                endpoint: string;
                keys: { p256dh: string; auth: string };
              },
            )
            .catch(() => {});
        }
      })
      .catch(() => {});
  }, []);

  const activePin = currentPinData?.pin ?? null;

  const pinAutoGenerated = React.useRef(false);

  useEffect(() => {
    if (
      currentPinData !== undefined &&
      currentPinData.pin === null &&
      !pinAutoGenerated.current &&
      !isGenerating
    ) {
      pinAutoGenerated.current = true;
      generatePin(undefined, {
        onSuccess: () =>
          queryClient.invalidateQueries({ queryKey: HOME_QUERY_KEYS.currentPin }),
      });
    }
  }, [currentPinData]);

  const stickyHeaderHeight = insets.top + TOP_BAR_HEIGHT;

  const scrollY = useRef(new Animated.Value(0)).current;
  const headerTranslateY = useRef(new Animated.Value(0)).current;
  const lastScrollY = useRef(0);
  const isHeaderVisible = useRef(true);

  const handleScroll = Animated.event(
    [{ nativeEvent: { contentOffset: { y: scrollY } } }],
    {
      useNativeDriver: true,
      listener: (event: NativeSyntheticEvent<NativeScrollEvent>) => {
        const y = event.nativeEvent.contentOffset.y;
        const diff = y - lastScrollY.current;

        if (diff > 10 && y > stickyHeaderHeight && isHeaderVisible.current) {
          isHeaderVisible.current = false;
          Animated.timing(headerTranslateY, {
            toValue: -stickyHeaderHeight,
            duration: 200,
            useNativeDriver: true,
          }).start();
        } else if ((diff < -5 || y <= 0) && !isHeaderVisible.current) {
          isHeaderVisible.current = true;
          Animated.timing(headerTranslateY, {
            toValue: 0,
            duration: 200,
            useNativeDriver: true,
          }).start();
        }

        lastScrollY.current = y;
      },
    },
  );

  const handleGeneratePin = () => {
    generatePin(undefined, {
      onSuccess: () =>
        queryClient.invalidateQueries({ queryKey: HOME_QUERY_KEYS.currentPin }),
    });
  };

  const bookingUrl = barbershop?.slug
    ? `${process.env.EXPO_PUBLIC_WEB_URL}/${barbershop.slug}`
    : null;

  const timezone = barbershop?.timezone ?? Intl.DateTimeFormat().resolvedOptions().timeZone;

  const todayOpenHours = React.useMemo(() => {
    const dayMap: Record<string, number> = {
      Sun: 0, Mon: 1, Tue: 2, Wed: 3, Thu: 4, Fri: 5, Sat: 6,
    };
    const parts = new Intl.DateTimeFormat('en-US', {
      timeZone: timezone,
      weekday: 'short',
    }).formatToParts(new Date());
    const localDay = parts.find((p) => p.type === 'weekday')?.value;
    const dayOfWeek = localDay ? dayMap[localDay] ?? new Date().getDay() : new Date().getDay();
    return openHoursData?.find((d) => d.dayOfWeek === dayOfWeek) ?? null;
  }, [openHoursData, timezone]);

  const isCurrentlyOpen = React.useMemo(() => {
    if (!todayOpenHours || !todayOpenHours.isOpen) return false;
    const open = todayOpenHours.openTime
      ? parseTime24(todayOpenHours.openTime)
      : null;
    const close = todayOpenHours.closeTime
      ? parseTime24(todayOpenHours.closeTime)
      : null;
    if (!open || !close) return false;
    const parts = new Intl.DateTimeFormat('en-US', {
      timeZone: timezone,
      hour: '2-digit',
      minute: '2-digit',
      hour12: false,
    }).formatToParts(new Date());
    let nowMinutes = 0;
    for (const p of parts) {
      if (p.type === 'hour') nowMinutes += parseInt(p.value) * 60;
      else if (p.type === 'minute') nowMinutes += parseInt(p.value);
    }
    const openMinutes = open.hour24 * 60 + open.minute;
    const closeMinutes = close.hour24 * 60 + close.minute;
    return nowMinutes >= openMinutes && nowMinutes < closeMinutes;
  }, [todayOpenHours, timezone]);

  const handleShareLink = async () => {
    if (!bookingUrl) return;
    const shareData = {
      title: t("home.walkinCheckinTitle"),
      text: t("home.walkinCheckinText"),
      url: bookingUrl,
    };
    try {
      if (typeof navigator !== "undefined" && navigator.share) {
        await navigator.share(shareData);
      } else {
        await Clipboard.setStringAsync(bookingUrl);
        toast.success(t("home.linkCopied"));
      }
    } catch (err) {
      if (err instanceof Error && err.name === "AbortError") return;
      toast.error(t("home.shareLinkFailed"));
    }
  };

  const waitingBookings = activeBookings
    .filter((b) => b.status === "waiting")
    .slice(0, 2);

  const handleBookingPress = (bookingId: string) => {
    router.push({ pathname: "/d/booking-detail", params: { id: bookingId } });
  };

  const statValues: Record<string, number> = {
    walkIn: summary?.walkIn ?? 0,
    appointment: summary?.appointment ?? 0,
    inProgress: summary?.inProgress ?? 0,
    waiting: summary?.waiting ?? 0,
  };

  const avatarInitials = user?.name
    ? user.name
        .split(" ")
        .slice(0, 2)
        .filter(Boolean)
        .map((w: string) => w[0].toUpperCase())
        .join("")
    : "";

  return (
    <View style={styles.root}>
      <Animated.ScrollView
        style={styles.scroll}
        showsVerticalScrollIndicator={false}
        contentContainerStyle={[
          styles.scrollContent,
          { paddingBottom: insets.bottom + 100 },
        ]}
        onScroll={handleScroll}
        scrollEventThrottle={16}
      >
        <View style={[styles.page, { paddingTop: stickyHeaderHeight + 36 }]}>
          {/* Greeting + Today&apos;s Hours */}
          <View style={styles.greetingSection}>
            <View style={styles.greetingLeft}>
              <AppText style={styles.greetingName}>{t("home.greeting", { name: user?.name ?? "..." })}</AppText>
              {role ? (
                <View style={styles.rolePillContainer}>
                  <AppText style={styles.rolePill}>{role}</AppText>
                </View>
              ) : null}
            </View>

            <TouchableOpacity
              activeOpacity={0.85}
              onPress={() => router.push("/d/open-hours")}
              style={styles.openHoursCard}
            >
              <AppText style={styles.openHoursTitle}>{t("home.todayHours")}</AppText>
              <View style={styles.openHoursStatusRow}>
                <View
                  style={[
                    styles.openHoursDot,
                    {
                      backgroundColor: isCurrentlyOpen
                        ? Colors.status.success
                        : Colors.status.danger,
                    },
                  ]}
                />
                <AppText style={styles.openHoursStatus}>
                  {isCurrentlyOpen ? t("barbershop.open") : t("barbershop.closed")}
                </AppText>
              </View>
              <AppText style={styles.openHoursRange}>
                {todayOpenHours
                  ? formatTimeRange(todayOpenHours.openTime, todayOpenHours.closeTime)
                  : "—"}
              </AppText>
            </TouchableOpacity>
          </View>

          {/* Quick Actions */}
          <View style={styles.quickActionsRow}>
            <Animated.ScrollView
              horizontal
              showsHorizontalScrollIndicator={false}
              contentContainerStyle={styles.quickActionsScroll}
            >
            <ShortcutTile
              label={t("home.newBooking")}
              variant="small"
              icon={
                <Ionicons
                  name="calendar-outline"
                  size={22}
                  color={Colors.text.primary}
                />
              }
              onPress={() => setNewBookVisible(true)}
            />
            <ShortcutTile
              label={t("home.requests")}
              variant="small"
              badgeCount={requestCount}
              icon={
                <Ionicons
                  name="calendar-number-outline"
                  size={22}
                  color={Colors.text.primary}
                />
              }
              onPress={() => router.push("/d/booking-requests")}
            />
            <ShortcutTile
              label={t("barbers.title")}
              variant="small"
              icon={
                <Ionicons
                  name="people-outline"
                  size={22}
                  color={Colors.text.primary}
                />
              }
              onPress={() => router.push("/d/barbers-management")}
            />
            <ShortcutTile
              label={t("customers.title")}
              variant="small"
              icon={
                <Ionicons
                  name="person-outline"
                  size={22}
                  color={Colors.text.primary}
                />
              }
              onPress={() => router.push("/d/customer-management")}
            />
            <ShortcutTile
              label={t("services.title")}
              variant="small"
              icon={
                <Ionicons
                  name="cut-outline"
                  size={22}
                  color={Colors.text.primary}
                />
              }
              onPress={() => router.push("/d/services-management")}
            />
            <ShortcutTile
              label={t("home.openHours")}
              variant="small"
              icon={
                <Ionicons
                  name="time-outline"
                  size={22}
                  color={Colors.text.primary}
                />
              }
              onPress={() => router.push("/d/open-hours")}
            />
            </Animated.ScrollView>
          </View>

          {/* Walk-In Check-In */}
          <View style={styles.walkInCard}>
            <View style={styles.walkInHeader}>
              <AppText style={styles.walkInLabel}>{t("home.walkinCheckin")}</AppText>
              <View style={styles.walkInActions}>
                <TouchableOpacity
                  onPress={handleGeneratePin}
                  disabled={isGenerating}
                  style={styles.walkInIconBtn}
                >
                  {isGenerating ? (
                    <ActivityIndicator
                      size="small"
                      color={Colors.text.secondary}
                    />
                  ) : (
                    <Ionicons
                      name="refresh-outline"
                      size={20}
                      color={Colors.text.secondary}
                    />
                  )}
                </TouchableOpacity>
                <TouchableOpacity
                  onPress={() => router.push("/d/barbershop-qr")}
                  style={styles.walkInIconBtn}
                >
                  <Ionicons
                    name="qr-code-outline"
                    size={20}
                    color={Colors.text.secondary}
                  />
                </TouchableOpacity>
              </View>
            </View>

            <AppText style={styles.walkInPin} numberOfLines={1}>
              {activePin ?? "----"}
            </AppText>

            {bookingUrl && (
              <TouchableOpacity
                onPress={handleShareLink}
                onLongPress={() => {
                  Clipboard.setStringAsync(bookingUrl);
                  toast.success(t("home.linkCopied"));
                }}
                activeOpacity={0.7}
                style={styles.walkInLinkPill}
              >
                <AppText style={styles.walkInLinkText} numberOfLines={1}>
                  {bookingUrl}
                </AppText>
                <Ionicons
                  name="share-outline"
                  size={18}
                  color={Colors.text.secondary}
                />
              </TouchableOpacity>
            )}
          </View>

          {/* Today&apos;s Queue */}
          <View style={styles.sectionRow}>
            <AppText style={styles.sectionTitle}>{t("home.todayOverview")}</AppText>
            <TouchableOpacity onPress={() => router.push("/d/schedule")}>
              <AppText style={styles.seeAll}>{t("common.all")}</AppText>
            </TouchableOpacity>
          </View>
          <View style={styles.queueGrid}>
            {getStatConfig(t).map((s) => (
              <QueueStatCard
                key={s.key}
                label={s.label}
                icon={s.icon}
                value={statValues[s.key]}
                onPress={() => router.push("/d/schedule")}
              />
            ))}
          </View>

          {/* Up Next */}
          <View style={styles.sectionRow}>
            <AppText style={styles.sectionTitle}>{t("home.upNext")}</AppText>
            <TouchableOpacity onPress={() => router.push("/d/schedule")}>
              <AppText style={styles.seeAll}>{t("home.seeAll")}</AppText>
            </TouchableOpacity>
          </View>
          {waitingBookings.length > 0 ? (
            waitingBookings.map((booking, i) => {
              const timeDate =
                booking.type === "appointment" && booking.scheduledAt
                  ? new Date(booking.scheduledAt as Date)
                  : new Date(booking.createdAt as Date);
              return (
                <BookingCard
                  key={booking.id}
                  customerName={booking.customerName}
                  barberName={booking.barber?.name ?? "—"}
                  timeLabel={formatTime12h(timeDate)}
                  duration={`${booking.totalDuration} mins`}
                  status={mapApiStatusToBookingStatus(booking.status)}
                  bookingType={booking.type}
                  onPress={() => handleBookingPress(booking.id)}
                  style={
                    i < waitingBookings.length - 1 ? styles.cardMargin : undefined
                  }
                />
              );
            })
          ) : (
            <AppText style={styles.emptyText}>{t("home.noBookingsToday")}</AppText>
          )}
        </View>
      </Animated.ScrollView>

      {/* Sticky header */}
      <Animated.View
        style={[
          styles.stickyHeader,
          {
            height: stickyHeaderHeight,
            paddingTop: insets.top,
            transform: [{ translateY: headerTranslateY }],
          },
        ]}
      >
        <View style={styles.headerRow}>
          <Image
            source={require("@/public/cukkr-logo-trans.png")}
            style={styles.headerLogo}
            resizeMode="contain"
          />
          <TouchableOpacity
            style={styles.shopSwitcher}
            activeOpacity={0.7}
            onPress={() => setSwitcherVisible(true)}
          >
            <AppText style={styles.shopName} numberOfLines={1}>
              {barbershop?.name ?? "..."}
            </AppText>
            <View style={styles.shopSwitcherRight}>
              {otherOrgHasUnread && <View style={styles.shopDot} />}
              <Ionicons
                name={switcherVisible ? "chevron-up" : "chevron-down"}
                size={14}
                color={Colors.text.primary}
              />
            </View>
          </TouchableOpacity>
          <TouchableOpacity
            style={styles.notifBtn}
            onPress={async () => {
              if (
                typeof window === "undefined" ||
                !("Notification" in window)
              ) {
                router.push("/d/notifications-list");
                return;
              }
              if (Notification.permission === "denied") {
                router.push("/d/notifications-list");
                return;
              }
              if (Notification.permission === "default") {
                setNotifConsentVisible(true);
                return;
              }
              // Permission already granted — silently renew subscription then navigate
              try {
                const { subscription } =
                  await pwaNotificationService.requestPermission();
                if (subscription) {
                  notificationsService
                    .registerWebPush(
                      subscription as {
                        endpoint: string;
                        keys: { p256dh: string; auth: string };
                      },
                    )
                    .catch(() => {});
                }
                router.push("/d/notifications-list");
              } catch (err) {
                const msg =
                  err instanceof Error
                    ? err.message
                    : t("home.notifSetupFailed");
                toast.error(msg);
                setTimeout(() => router.push("/d/notifications-list"), 1500);
              }
            }}
          >
            <Ionicons
              name="notifications-outline"
              size={20}
              color={Colors.text.primary}
            />
            {(unreadCount ?? 0) > 0 ? <View style={styles.notifDot} /> : null}
          </TouchableOpacity>
          <TouchableOpacity
            style={styles.profileBtn}
            onPress={() => router.push("/d/user-profile")}
          >
            {user?.image ? (
              <Image
                source={{ uri: user.image }}
                style={styles.profileAvatar}
              />
            ) : (
              <AppText style={styles.profileInitials}>
                {avatarInitials}
              </AppText>
            )}
          </TouchableOpacity>
        </View>
      </Animated.View>

      {/* Modals */}
      <BarbershopSwitcherModal
        visible={switcherVisible}
        onClose={() => setSwitcherVisible(false)}
      />
      <NewBookBottomSheet
        visible={newBookVisible}
        onClose={() => setNewBookVisible(false)}
      />
      <ConfirmationModal
        visible={notifConsentVisible}
        icon="notifications"
        title={t("home.stayUpdated")}
        description={t("home.notifConsentDesc")}
        cancelLabel={t("home.enable")}
        confirmLabel={t("home.notNow")}
        onCancel={() => {
          setNotifConsentVisible(false);
          // Defer until after the modal overlay is fully removed from DOM,
          // otherwise some browsers block the native permission dialog.
          setTimeout(async () => {
            try {
              const { subscription } =
                await pwaNotificationService.requestPermission();
              if (subscription) {
                notificationsService
                  .registerWebPush(
                    subscription as {
                      endpoint: string;
                      keys: { p256dh: string; auth: string };
                    },
                  )
                  .catch(() => {});
              }
              router.push("/d/notifications-list");
            } catch (err) {
              const msg =
                err instanceof Error
                  ? err.message
                  : t("home.notifSetupFailed");
              toast.error(msg);
              setTimeout(() => router.push("/d/notifications-list"), 1500);
            }
          }, 300);
        }}
        onConfirm={() => {
          setNotifConsentVisible(false);
          router.push("/d/notifications-list");
        }}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: Colors.bg.default,
  },

  scroll: {
    flex: 1,
    backgroundColor: Colors.bg.default,
  },
  scrollContent: {
    backgroundColor: Colors.bg.default,
  },
  page: {
    backgroundColor: Colors.bg.default,
    paddingHorizontal: 20,
    paddingBottom: 20,
  },

  // Greeting
  greetingSection: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginHorizontal: 24,
    gap: 12,
    marginBottom: 36,
  },
  greetingLeft: {
    flex: 1,
  },
  greetingSmall: {
    fontSize: 13,
    color: Colors.text.secondary,
    fontWeight: "500",
  },
  greetingName: {
    fontSize: 22,
    fontWeight: "800",
    color: Colors.text.primary,
    letterSpacing: -0.5,
  },
  rolePillContainer: {
    alignSelf: "flex-start",
    backgroundColor: Colors.brand.primarySurface,
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 3,
    marginTop: 4,
  },
  rolePill: {
    fontSize: 11,
    fontWeight: "700",
    color: Colors.brand.primaryDark,
    textTransform: "capitalize",
  },
  openHoursCard: {
    backgroundColor: Colors.bg.surface,
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 14,
    minWidth: 120,
    alignItems: "flex-start",
    gap: 4,
  },
  openHoursTitle: {
    fontSize: 12,
    fontWeight: "600",
    color: Colors.text.muted,
  },
  openHoursStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  openHoursDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  openHoursStatus: {
    fontSize: 15,
    fontWeight: "700",
    color: Colors.text.primary,
  },
  openHoursRange: {
    fontSize: 12,
    fontWeight: "500",
    color: Colors.text.secondary,
  },

  // Sticky header
  stickyHeader: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: Colors.bg.default,
    zIndex: 10,
  },
  headerRow: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    gap: 10,
  },
  headerLogo: {
    width: 28,
    height: 28,
  },
  shopSwitcher: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  shopSwitcherRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  shopDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.status.danger,
  },
  shopName: {
    maxWidth: 120,
    fontSize: 14,
    fontWeight: "700",
    color: Colors.text.primary,
    letterSpacing: -0.3,
  },
  notifBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: Colors.border.default,
    backgroundColor: Colors.bg.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  notifDot: {
    position: "absolute",
    top: 4,
    right: 4,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.status.danger,
  },
  profileBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: Colors.border.default,
    backgroundColor: Colors.bg.surface,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  profileAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  profileInitials: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.brand.primaryDark,
  },

  // Quick Actions
  quickActionsRow: {
    marginTop: 16,
    marginBottom: 24,
  },
  quickActionsScroll: {
    flexDirection: "row",
    gap: 20,
    paddingVertical: 4,
  },

  // Walk-In Check-In
  walkInCard: {
    backgroundColor: Colors.bg.surface,
    borderRadius: 20,
    padding: 16,
    marginBottom: 24,
  },
  walkInHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  walkInLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: Colors.text.secondary,
    letterSpacing: 1,
  },
  walkInActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  walkInIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.bg.default,
    alignItems: "center",
    justifyContent: "center",
  },
  walkInPin: {
    fontSize: 48,
    fontWeight: "800",
    color: Colors.text.primary,
    letterSpacing: 4,
    marginBottom: 12,
  },
  walkInLinkPill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.bg.default,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 8,
    marginBottom: 12,
  },
  walkInLinkText: {
    flex: 1,
    fontSize: 13,
    color: Colors.text.secondary,
    fontWeight: "500",
  },
  // Section
  sectionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
    paddingHorizontal: 2,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: Colors.text.primary,
  },
  seeAll: {
    fontSize: 13,
    color: Colors.brand.primaryDark,
    fontWeight: "500",
  },

  // Today&apos;s Queue
  queueGrid: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 28,
  },

  cardMargin: {
    marginBottom: 12,
  },
  emptyText: {
    fontSize: 13,
    color: Colors.text.muted,
    textAlign: "center",
    marginTop: 16,
    paddingHorizontal: 16,
  },
});
